/** Boutiques RACÈLIA — points de vente (Algérie). */
export const STORE_TYPES = [
  { value: "flagship", label: "Boutique phare" },
  { value: "boutique", label: "Boutique" },
  { value: "corner", label: "Corner" },
  { value: "atelier", label: "Atelier" },
];

export const RACELIA_STORES = [
  {
    id: "alger-didouche",
    name: "RACÈLIA Alger — Didouche Mourad",
    type: "flagship",
    address: "24 boulevard Didouche Mourad, Alger Centre",
    city: "Alger",
    postal: "16000",
    phone: "+213 21 00 00 01",
    website: "https://racelia.com",
    hours: "Lun–Sam 10h–19h · Dim 11h–17h",
    note: "Boutique phare — collection complète et services personnalisés.",
    lat: 36.7753,
    lng: 3.0588,
  },
  {
    id: "alger-hydracity",
    name: "RACÈLIA Alger — Hydra",
    type: "boutique",
    address: "Chemin Mackley, Hydra, Alger",
    city: "Alger",
    postal: "16035",
    phone: "+213 21 00 00 02",
    website: "https://racelia.com",
    hours: "Lun–Sam 10h–19h",
    note: "Essai et conseils d’entretien.",
    lat: 36.7472,
    lng: 3.0365,
  },
  {
    id: "oran-front-de-mer",
    name: "RACÈLIA Oran — Front de mer",
    type: "boutique",
    address: "Boulevard de la Soummam, Oran",
    city: "Oran",
    postal: "31000",
    phone: "+213 41 00 00 03",
    website: "https://racelia.com",
    hours: "Lun–Sam 10h–19h · Dim fermé",
    note: "Livraison express disponible depuis cette boutique.",
    lat: 35.6971,
    lng: -0.6308,
  },
  {
    id: "constantine-centre",
    name: "RACÈLIA Constantine",
    type: "corner",
    address: "Avenue Aouati Mostefa, Constantine",
    city: "Constantine",
    postal: "25000",
    phone: "+213 31 00 00 04",
    website: "https://racelia.com",
    hours: "Lun–Sam 10h–18h30",
    note: "Corner partenaire — sélection saisonnière.",
    lat: 36.365,
    lng: 6.6147,
  },
  {
    id: "blida-centre",
    name: "RACÈLIA Blida",
    type: "boutique",
    address: "Rue des Frères Bouadou, Blida",
    city: "Blida",
    postal: "09000",
    phone: "+213 25 00 00 05",
    website: "https://racelia.com",
    hours: "Lun–Sam 10h–19h",
    note: null,
    lat: 36.47,
    lng: 2.8277,
  },
  {
    id: "setif-atelier",
    name: "Atelier RACÈLIA Sétif",
    type: "atelier",
    address: "Zone industrielle, Sétif",
    city: "Sétif",
    postal: "19000",
    phone: "+213 36 00 00 06",
    website: "https://racelia.com",
    hours: "Sur rendez-vous",
    note: "Visites d’atelier sur rendez-vous uniquement.",
    lat: 36.1911,
    lng: 5.4137,
  },
];

export function storeTypeLabel(type) {
  return STORE_TYPES.find((t) => t.value === type)?.label || type;
}
