/** Built-in catalog seed — no imports from productCatalog to avoid cycles. */

const img = {
  bag1: "https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=800&q=80",
  bag2: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
  bag3: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=80",
  bag4: "https://images.unsplash.com/photo-1547949003-9792a18a2601?auto=format&fit=crop&w=800&q=80",
  bag5: "https://images.unsplash.com/photo-1606522754091-a3bbf9ad4cef?auto=format&fit=crop&w=800&q=80",
  bag6: "https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=800&q=80",
  editorial: "https://images.unsplash.com/photo-1483653364400-eedcfb9f1f88?auto=format&fit=crop&w=1000&q=80",
};

function p(data) {
  return {
    stockNote: "",
    tag: "",
    isPack: false,
    packLabel: "",
    description: "",
    materials: "Refined pebble leather. Wipe with a soft, dry cloth.",
    size: "Dimensions and strap drop vary by style.",
    filters: [],
    closerLookMain: {
      image: img.editorial,
      title: "A Closer Look",
      text: "Refined pebble leather with a polished finish — casual meets dressy, designed for everyday elegance.",
    },
    ...data,
    coverImage: data.coverImage || data.cardImages?.[0] || "",
    cardImages: data.cardImages || [],
    closerLookImages: data.closerLookImages || [],
    colors: data.colors || [],
    sections: data.sections || ["all-selection"],
  };
}

export function getBuiltInCatalogProducts() {
  return [
    p({
      id: "mini-flap-bag",
      name: "MINI FLAP BAG",
      tag: "Métiers d'Art",
      price: "€ 3,950",
      isNewArrival: true,
      stockNote: "new",
      coverImage: img.bag1,
      cardImages: [img.bag1, img.bag3, img.bag4, img.bag5],
      closerLookImages: [img.bag3, img.bag4],
      colors: ["#5a4a36", "#111", "#f1ece2", "#7a1f1f", "#6b8aa8", "#c4a882"],
      filters: ["2026 Métiers d'art", "Leather", "Black", "Gold-Tone"],
      sections: ["mini-bags", "all-selection", "metiers-dart"],
      description: "The Mini Flap Bag features signature RACÈLIA hardware and a compact silhouette for day-to-night wear.",
      size: "Width: 20 cm · Height: 14 cm · Depth: 6 cm. Detachable crossbody strap included.",
    }),
    p({
      id: "mini-hobo-bag",
      name: "MINI HOBO BAG",
      tag: "SS26",
      price: "€ 4,200",
      stockNote: "dispo",
      coverImage: img.bag3,
      cardImages: [img.bag3, img.bag1, img.bag6, img.bag2],
      closerLookImages: [img.bag1, img.bag6],
      colors: ["#111", "#7a1f1f", "#f1ece2"],
      filters: ["Spring Summer 2026", "Leather", "Red", "Silver-Tone"],
      sections: ["mini-bags", "all-selection"],
      description: "Soft hobo silhouette with adjustable strap and interior card slots.",
    }),
    p({
      id: "mini-evening-clutch",
      name: "MINI EVENING CLUTCH",
      tag: "Evening",
      price: "€ 2,850",
      stockNote: "dispo",
      coverImage: img.bag5,
      cardImages: [img.bag5, img.bag4, img.bag3],
      closerLookImages: [img.bag4, img.bag3],
      colors: ["#6b8aa8", "#111", "#f1ece2", "#5a4a36", "#7a1f1f"],
      filters: ["The Emblematics", "Tweed & Fabrics", "Blue", "Gold-Tone", "On a look"],
      sections: ["mini-bags", "all-selection"],
      description: "Compact evening clutch with chain strap and magnetic closure.",
    }),
    p({
      id: "racelia-classic",
      name: "THE RACÈLIA CLASSIC",
      tag: "Signature",
      price: "€ 5,700",
      isNewArrival: true,
      stockNote: "new",
      coverImage: img.bag2,
      cardImages: [img.bag2, img.bag4, img.bag6, img.bag1, img.bag3],
      closerLookImages: [img.bag4, img.bag6],
      colors: ["#6b8aa8", "#111", "#f1ece2", "#5a4a36", "#7a1f1f", "#c4a882", "#2f4f4f"],
      filters: ["2026 Métiers d'art", "Leather", "Beige", "Gold-Tone"],
      sections: ["racelia-handbag", "all-selection", "metiers-dart"],
      description: "Signature RACÈLIA hardware, a top handle and a detachable crossbody strap for versatile day-to-evening wear.",
    }),
    p({
      id: "racelia-maxi-flap",
      name: "RACÈLIA MAXI FLAP",
      tag: "Pre-collection",
      price: "€ 6,400",
      stockNote: "dispo",
      coverImage: img.bag4,
      cardImages: [img.bag4, img.bag2, img.bag5],
      closerLookImages: [img.bag2, img.bag5],
      colors: ["#5a4a36", "#111"],
      filters: ["Spring Summer 2026 Pre-collection", "Leather", "Black", "Silver-Tone"],
      sections: ["racelia-handbag", "all-selection"],
      description: "Oversized flap silhouette with double-compartment interior.",
    }),
    p({
      id: "racelia-signature-tote",
      name: "RACÈLIA SIGNATURE TOTE",
      tag: "SS26",
      price: "€ 5,200",
      stockNote: "sold-out",
      coverImage: img.bag6,
      cardImages: [img.bag6, img.bag3, img.bag1, img.bag4],
      closerLookImages: [img.bag3, img.bag1],
      colors: ["#111", "#f1ece2", "#7a1f1f"],
      filters: ["Spring Summer 2026", "Tweed & Fabrics", "Red", "Gold-Tone"],
      sections: ["racelia-handbag", "all-selection"],
      description: "Structured tote with reinforced base and interior zip pocket.",
    }),
    p({
      id: "mom-tote",
      name: "MOM TOTE",
      tag: "Métiers d'Art",
      price: "€ 4,650",
      stockNote: "dispo",
      coverImage: img.bag4,
      cardImages: [img.bag4, img.bag5, img.bag2, img.bag6],
      closerLookImages: [img.bag5, img.bag2],
      colors: ["#5a4a36", "#111", "#f1ece2", "#6b8aa8", "#7a1f1f"],
      filters: ["2026 Métiers d'art", "Leather", "Beige", "Gold-Tone", "On a look"],
      sections: ["moms-bags", "all-selection", "metiers-dart"],
      description: "Spacious tote designed for everyday elegance with multiple carry options.",
    }),
    p({
      id: "mom-shoulder-bag",
      name: "MOM SHOULDER BAG",
      tag: "Emblematics",
      price: "€ 4,950",
      stockNote: "dispo",
      coverImage: img.bag5,
      cardImages: [img.bag5, img.bag1, img.bag3],
      closerLookImages: [img.bag1, img.bag3],
      colors: ["#111", "#6b8aa8"],
      filters: ["The Emblematics", "Leather", "Blue", "Silver-Tone"],
      sections: ["moms-bags", "all-selection"],
      description: "Shoulder bag with wide strap and soft-structure silhouette.",
    }),
    p({
      id: "mom-crossbody",
      name: "MOM CROSSBODY",
      tag: "SS26 Pre-collection",
      price: "€ 3,800",
      stockNote: "not",
      coverImage: img.bag1,
      cardImages: [img.bag1, img.bag6, img.bag4, img.bag2],
      closerLookImages: [img.bag6, img.bag4],
      colors: ["#7a1f1f", "#111", "#f1ece2", "#5a4a36", "#6b8aa8", "#c4a882"],
      filters: ["Spring Summer 2026 Pre-collection", "Tweed & Fabrics", "Yellow", "Gold-Tone"],
      sections: ["moms-bags", "all-selection"],
      description: "Crossbody with adjustable woven strap and front flap pocket.",
    }),
  ];
}
